#
# config file for FLIR A50/A70 cameras (GigE)
#
# this file maps the ROS2 parameters to the corresponding Spinnaker "nodes" in the camera.
# this file is based on the config files provided in the ros-drivers/flir_camera_driver:humble-devel directory.

parameters:
  #
  # -------- image format control
  #
  - name: pixel_format
    type: enum
    # default is "Mono8"
    node: ImageFormatControl/PixelFormat
  - name: image_width
    type: int
    node: ImageFormatControl/Width
  - name: image_height
    type: int
    node: ImageFormatControl/Height
  - name: offset_x # offset must come after image width reduction!
    type: int
    node: ImageFormatControl/OffsetX
  - name: offset_y
    type: int
    node: ImageFormatControl/OffsetY
  - name: image_packet_format
    type: enum
    # default is "H264Data; valid values: "H264Data", "ImageData"
    node: ImageFormatControl/H264PacketFormat


  #
  # -------- acquisition control
  #
  - name: exposure_auto
    type: enum
    # valid values are "Off", "Continuous"
    node: AcquisitionControl/ExposureAuto
  - name: exposure_time
    type: float
    node: AcquisitionControl/ExposureTime
  - name: frame_rate_enable
    type: bool
    node: AcquisitionControl/AcquisitionFrameRateEnable
  - name: frame_rate
    type: float
    node: AcquisitionControl/AcquisitionFrameRate


  #
  # -------- transport layer control (GigE)
  #
  - name: gev_scps_packet_size
    type: int
    # default is 576. Other cameras had the option to set to 9000 to enable jumbo frames, ensure NIC MTU set >= 9000
    node: TransportLayerControl/GevSCPSPacketSize


  # 
  # ---------- FLIR Camera Control
  #
  - name: nuc_mode # Non-uniformity Control closes the shutter and recalibrates
    type: enum
    # valid values: "Automatic", "External", "Manual"
    node: CameraControl/NUCMode


  #
  # --------- FLIR Stream Control
  #
  - name: ir_pixel_format
    type: enum
    # default is "Radiometric"; valid options: "Radiometric", "TemperatureLinear100mK", "TemperatureLinear10mK"
    node: ImageStreamControl/IRFormat
  - name: ir_frame_rate
    type: enum
    # default is "Frame30Hz; valid values: "Frame60Hz", "Frame30Hz", "Frame15Hz", "Frame7Hz", "Frame4Hz"
    node: ImageStreamControl/IRFrameRate
